### ISSUE TITLE
Power Spctrum Error

### ISSUE THREAD

**Issue by Daniel78-usp** [embar-/eeglab_darbeliai#70] opened 2023-04-30 19:11 UTC
Please help!
I'm using MATLAB R2022b and EEGLAB v2023.0. In my case the Signal Processing Toolbox is installed, but I keep getting the following error:
Darbeliai v2019.02.01.1
EEGLAB 2023.0
MATLAB 9.13.0.2080170 (R2022b) Update 1 Windows en_US
 
---------------
 Time: 2023-04-30 15:54:15
Job: EEG spectrum and power
Filet: ?
 
Error! Please read info in console.

> eeg_spektr_galia:360
> checkbox_perziura_Callback:1867
> gui_mainfcn:95
> pop_eeg_spektrine_galia:88
  @(hObject,eventdata)pop_eeg_spektrine_galia('checkbox_perziura_Callback',hObject,eventdata,guidata(hObject))

 ---------------
Warning: MATLAB:UndefinedFunction

Unrecognized function or variable 'eegspec'.

> spectcomp:982
> spectopo:347
> pop_spectopo:331
> eeg_spektr_galia:246
> checkbox_perziura_Callback:1867
> gui_mainfcn:95
> pop_eeg_spektrine_galia:88

  @(hObject,eventdata)pop_eeg_spektrine_galia('checkbox_perziura_Callback',hObject,eventdata,guidata(hObject))  Warning:

Error! Please read info in console.

> eeg_spektr_galia:360
> checkbox_perziura_Callback:1867
> gui_mainfcn:95
> pop_eeg_spektrine_galia:88

   @(hObject,eventdata)pop_eeg_spektrine_galia('checkbox_perziura_Callback',hObject,eventdata,guidata(hObject))

**Comment by embar-** [comment] 2024-07-26 08:51
Sorry for late answer. 

Darbeliai here is just a wrapper for the EEGLAB  built-in function-file "pop_spectopo.m" where your error occurred. Seems some conditions were not met and thus "eegspec" variable was not declared within spectcomp function within "pop_spectopo.m". Make sure your dataset has sufficient amount of data. 

If you still have this bug, please inform EEGLAB team at https://github.com/sccn/eeglab/issues and provide EEG dataset for testing.

Closing as not a bug of Darbeliai.

**Closed** 2024-07-26 08:52 UTC
